name: Upload DAGs to GCS

on:
  push:
    branches:
      - main  # Change if you want a different branch to trigger the action

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Upload DAGs to GCS
        run: |
          gsutil -m cp -r ./dags gs://dp-airflow-dags/
